// vuejs/src/components/TodoList.vue
<template>
    <div class="todo-list">
      <h1>My To-Do List</h1>
      <input v-model="newTaskText" placeholder="Add a new task..." />
      <button @click="addTask">Add</button>
      <ul>
        <li v-for="task in tasks" :key="task.id">
          <TodoItem
            :task="task"
            @delete-task="deleteTask"
            @toggle-completed="toggleCompleted"
            @update-task-text="updateTaskText"
          />
        </li>
      </ul>
    </div>
  </template>
  
  <script>
  import TodoItem from './TodoItem.vue';
  
  export default {
    components: {
      TodoItem,
    },
    data() {
      return {
        newTaskText: '',
        tasks: [
          { id: 1, text: 'Doctor Appointment', completed: true },
          { id: 2, text: 'Meeting at School', completed: false },
        ],
      };
    },
    methods: {
      addTask() {
        if (this.newTaskText.trim()) {
          this.tasks.push({
            id: Date.now(),
            text: this.newTaskText.trim(),
            completed: false,
          });
          this.newTaskText = '';
        }
      },
      deleteTask(id) {
        this.tasks = this.tasks.filter((task) => task.id !== id);
      },
      toggleCompleted(id) {
        const task = this.tasks.find((task) => task.id === id);
        if (task) {
          task.completed = !task.completed;
        }
      },
      updateTaskText(id, newText) {
        const task = this.tasks.find((task) => task.id === id);
        if (task) {
          task.text = newText;
        }
      },
    },
  };
  </script>
  
  <style scoped>
  .todo-list {
    max-width: 500px;
    margin: 0 auto;
    padding: 20px;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  }
  
  input[type="text"] {
    width: calc(100% - 85px);
    padding: 10px;
    margin-bottom: 10px;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    transition: border-color 0.3s;
  }
  
  input[type="text"]:focus {
    border-color: #5cb85c;
    outline: none;
  }
  
  button {
    padding: 10px 20px;
    background-color: #5cb85c;
    color: white;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    font-size: 16px;
    transition: background-color 0.3s, transform 0.2s;
  }
  
  button:hover {
    background-color: #4cae4c;
    transform: scale(1.05);
  }
  
  button:active {
    background-color: #4cae4c;
    transform: scale(1.02);
  }
  
  ul {
    list-style-type: none;
    padding: 0;
  }
  
  li {
    margin: 5px 0;
  }
  </style>

// reactjs/src/components/TodoList.js
// TodoList.js

// TodoList.js

import React, { useState } from 'react';
import TodoItem from './TodoItem';
import './TodoList.css'; // Import TodoList-specific styles

function TodoList() {
  // State to manage the list of tasks
  const [tasks, setTasks] = useState([
    {
      id: 1,
      text: 'Doctor Appointment',
      completed: true,
    },
    {
      id: 2,
      text: 'Meeting at School',
      completed: false,
    },
  ]);

  // State to manage the input for new tasks
  const [text, setText] = useState('');

  // Function to add a new task
  function addTask(text) {
    const newTask = {
      id: Date.now(), // Unique identifier for the task
      text,
      completed: false,
    };
    setTasks([...tasks, newTask]);
    setText(''); // Clear input after adding the task
  }

  // Function to delete a task by id
  function deleteTask(id) {
    setTasks(tasks.filter((task) => task.id !== id));
  }

  // Function to toggle the completed status of a task
  function toggleCompleted(id) {
    setTasks(
      tasks.map((task) => {
        if (task.id === id) {
          return { ...task, completed: !task.completed };
        } else {
          return task;
        }
      })
    );
  }

  // Function to update the text of a task
  function updateTaskText(id, newText) {
    setTasks(
      tasks.map((task) => {
        if (task.id === id) {
          return { ...task, text: newText };
        } else {
          return task;
        }
      })
    );
  }

  return (
    <div className="todo-list">
      <ul>
        {tasks.map((task) => (
          <li key={task.id}>
            <TodoItem
              task={task}
              deleteTask={deleteTask}
              toggleCompleted={toggleCompleted}
              updateTaskText={updateTaskText}
            />
          </li>
        ))}
      </ul>
      <input
        value={text}
        onChange={(e) => setText(e.target.value)}
        placeholder="Add a new task..."
      />
      <button onClick={() => addTask(text)}>Add</button>
    </div>
  );
}

export default TodoList;
