// reactjs/src/components/TodoItem.js
// TodoItem.js

// TodoItem.js

import React, { useState } from 'react';
import './TodoItem.css'; // Import TodoItem-specific styles

function TodoItem({ task, deleteTask, toggleCompleted, updateTaskText }) {
  // State to manage edit mode and input text
  const [isEditing, setIsEditing] = useState(false);
  const [editText, setEditText] = useState(task.text);

  // Toggle edit mode
  const handleEditToggle = () => {
    setIsEditing(!isEditing);
    setEditText(task.text); // Reset edit text to current task text
  };

  // Handle task text update
  const handleUpdate = () => {
    updateTaskText(task.id, editText); // Update task text
    setIsEditing(false); // Exit edit mode
  };

  return (
    <div className="todo-item">
      <input
        type="checkbox"
        checked={task.completed}
        onChange={() => toggleCompleted(task.id)}
      />
      {isEditing ? (
        <input
          type="text"
          value={editText}
          onChange={(e) => setEditText(e.target.value)}
          onKeyDown={(e) => e.key === 'Enter' && handleUpdate()}
        />
      ) : (
        <span
          style={{ textDecoration: task.completed ? 'line-through' : 'none' }}
          onClick={() => toggleCompleted(task.id)}
        >
          {task.text}
        </span>
      )}
      {isEditing ? (
        <button onClick={handleUpdate}>Save</button>
      ) : (
        <button onClick={handleEditToggle}>Edit</button>
      )}
      <button onClick={() => deleteTask(task.id)}>Delete</button>
    </div>
  );
}

export default TodoItem;

// angular/src/app/todo-item/todo-item.component.ts
// src/app/todo-item/todo-item.component.ts

import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

interface Task {
  id: number;
  text: string;
  completed: boolean;
}

@Component({
  selector: 'app-todo-item',
  standalone: true,  // Mark as standalone
  imports: [CommonModule, FormsModule], // Include necessary modules
  templateUrl: './todo-item.component.html',
  styleUrls: ['./todo-item.component.css']
})
export class TodoItemComponent {
  @Input() task!: Task;
  @Output() delete = new EventEmitter<number>();
  @Output() toggleCompleted = new EventEmitter<number>();
  @Output() updateText = new EventEmitter<{ id: number; text: string }>();

  isEditing: boolean = false;
  editText: string = '';

  ngOnInit() {
    this.editText = this.task.text;
  }

  toggleEdit() {
    this.isEditing = !this.isEditing;
    this.editText = this.task.text;
  }

  saveEdit() {
    if (this.editText.trim()) {
      this.updateText.emit({ id: this.task.id, text: this.editText.trim() });
      this.isEditing = false;
    }
  }

  cancelEdit() {
    this.isEditing = false;
  }
}

<!-- todo-item.component.html -->

<div class="todo-item">
    <input
      type="checkbox"
      [checked]="task.completed"
      (change)="toggleCompleted.emit(task.id)"
    />
    <ng-container *ngIf="isEditing">
      <input
        type="text"
        [(ngModel)]="editText"
        (keydown.enter)="saveEdit()"
      />
      <button (click)="saveEdit()">Save</button>
      <button (click)="cancelEdit()">Cancel</button>
    </ng-container>
    <ng-container *ngIf="!isEditing">
      <span
        [style.textDecoration]="task.completed ? 'line-through' : 'none'"
        (click)="toggleCompleted.emit(task.id)"
      >
        {{ task.text }}
      </span>
      <button (click)="toggleEdit()">Edit</button>
      <button (click)="delete.emit(task.id)">Delete</button>
    </ng-container>
  </div>
